Repository staratlas-italia/frontend, pull requests merged in 2022-01, with the labels that each got.

#3 [Docs] Update readmes
  .env.dist
  README.md
  docs/README_EN.md
Labels: documentation

#4 Update README badges
  README.md
Labels: documentation

#5 Add full Solana wallets support
  src/components/List/components/Item/index.tsx
  src/components/List/components/Section/index.tsx
  src/components/List/index.tsx
  src/components/Wallet/components/ConnectButton/index.tsx
  src/components/Wallet/components/UserBadge/index.tsx
  src/components/Wallet/index.tsx
  src/components/controls/Button/index.tsx
  src/components/layout/BaseLayout/index.tsx
  src/components/layout/Header/index.tsx
  src/components/modals/BaseModal/index.tsx
  src/components/modals/WalletModal/components/ConnectedContent/index.tsx
  src/components/modals/WalletModal/components/DisconnectedContent/index.tsx
  src/components/modals/WalletModal/index.tsx
  src/components/pages/Ship/index.tsx
  src/contexts/ModalContext/index.tsx
  src/contexts/WalletProvider/index.tsx
  src/i18n/translations/en.json
  src/i18n/translations/it.json
  src/i18n/translations/types.ts
  src/network/ships/index.ts
  src/types/index.ts
Labels: enhancement

#6 Improve guild treasury view
  src/common/constants/index.tsx
  src/components/layout/BaseLayout/index.tsx
  src/components/layout/BlurBackground/index.tsx
  src/components/layout/Header/components/Treasury/index.tsx
  src/components/pages/Home/components/EnlistBanner/index.tsx
  src/components/pages/Home/components/WelcomeBanner/index.tsx
  src/components/pages/Home/index.tsx
  src/hooks/useGuildTreasury/index.tsx
Labels: enhancement

#7 Add SA score apis
  package.json
  src/common/constants/index.tsx
  src/pages/api/score/[pbk].ts
  src/pages/api/score/[pbk]/[mint].ts
  src/pages/api/score/rates/[mint].ts
  src/types/api.ts
  src/types/index.ts
  src/utils/connection/index.ts
  src/utils/pubkey/index.ts
  yarn.lock
Labels: enhancement

#8 Ship API cost and reward calc
  src/common/constants/index.tsx
  src/pages/api/score/[pbk].ts
  src/utils/dailyMaintenanceCostInAtlas/index.ts
  src/utils/grossDailyRewardInAtlas/index.ts
  src/utils/netDailyRewardInAtlas/index.ts
  src/utils/resDailyConsumption/index.ts
  src/utils/resDailyCostInAtlas/index.ts
Labels: enhancement

#10 Missing associated token account retrieving token balance
  src/common/constants/index.tsx
  src/hooks/useTokenBalance/index.ts
  src/utils/splToken/index.ts
Labels: bug

#13 Improve ships table
  src/components/common/Price/index.tsx
  src/i18n/translations/en.json
  src/i18n/translations/it.json
  src/i18n/translations/types.ts
  src/views/Ships/components/ShipTable/index.tsx
  src/views/Ships/components/ShipTable/utils/buildPriceColumn/index.tsx
Labels: enhancement

#14 Fix resources url
  src/components/layout/SideBarLayout/components/SideBar/components/Content/index.tsx
Labels: bug, enhancement

#15 Ships table apis improvement
  package.json
  src/components/common/Heading/index.tsx
  src/components/controls/ButtonGroup/index.tsx
  src/components/layout/SideBarLayout/components/SideBar/components/Content/index.tsx
  src/components/layout/SideBarLayout/components/SideBar/components/Footer/index.tsx
  src/components/layout/SideBarLayout/components/SideBar/index.tsx
  src/components/modals/ShipsModal/index.tsx
  src/contexts/ShipsContext/index.tsx
  src/hooks/useEntityBestPrices/index.ts
  src/hooks/useEntityLastPrice/index.ts
  src/hooks/useEntityVwapPrice/index.ts
  src/hooks/useNullableShips/index.tsx
  src/hooks/useShip/index.tsx
  src/hooks/useShips/index.tsx
  src/i18n/translations/en.json
  src/i18n/translations/it.json
  src/i18n/translations/types.ts
  src/views/Dashboard/components/Fleet/index.tsx
  src/views/Dashboard/index.tsx
  src/views/Home/components/EnlistBanner/index.tsx
  src/views/Home/components/WelcomeBanner/index.tsx
  src/views/Ship/index.tsx
  src/views/Ships/components/ShipList/index.tsx
  src/views/Ships/components/ShipTable/columns/index.tsx
  src/views/Ships/components/ShipTable/index.tsx
  src/views/Ships/components/ShipTable/useShipsTable/index.ts
  src/views/Ships/components/ShipsRetriever/index.tsx
  src/views/Ships/index.tsx
  yarn.lock
Labels: enhancement

#18 Firefox update all blur items
  src/components/List/components/Item/index.tsx
  src/components/layout/BlurBackground/index.tsx
  src/components/layout/SideBarLayout/components/SideBar/index.tsx
  src/components/layout/SideBarLayout/index.tsx
  src/i18n/translations/en.json
  src/i18n/translations/it.json
  src/i18n/translations/types.ts
  src/utils/isFirefox/index.ts
  src/views/Dashboard/index.tsx
  src/views/Home/components/WelcomeBanner/index.tsx
  src/views/Home/index.tsx
  src/views/Ships/components/Ship/index.tsx
Labels: bug

#20 Add the footer component
  src/components/layout/BaseLayout/index.tsx
  src/components/layout/Footer/components/Disclaimer/index.tsx
  src/components/layout/Footer/components/Links/index.tsx
  src/components/layout/Footer/index.tsx
  src/components/layout/SideBarLayout/index.tsx
  src/i18n/translations/en.json
  src/i18n/translations/it.json
  src/i18n/translations/types.ts
Labels: enhancement
